import React from 'react';
import ReactDOM from 'react-dom';
import App from './App';
import { Amplify } from 'aws-amplify';
import amplifyConfig from '../amplify_outputs.json'; // generated by Amplify Studio

Amplify.configure(amplifyConfig);

ReactDOM.render(<App />, document.getElementById('root'));
